# Generated by Django 4.0.4 on 2022-07-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя пользователя')),
                ('telegram_id', models.CharField(max_length=20, verbose_name='телеграм ИД')),
                ('telegram_username', models.CharField(max_length=50, verbose_name='телеграм имя')),
                ('is_speaker', models.BooleanField(default=False, verbose_name='докладчик')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='актуальный')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot.presentation')),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile'),
        ),
    ]
