# Generated by Django 4.0.4 on 2022-07-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_presentation_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='время начала')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='время окончания')),
                ('is_presentation', models.BooleanField(default=False, verbose_name='это доклад')),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bot.eventgroup')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='bot.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot.event'),
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
