# Generated by Django 4.0.4 on 2022-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_eventgroup_event_alter_question_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='None', verbose_name='ответ на вопрос'),
            preserve_default=False,
        ),
    ]
