# Generated by Django 4.0.4 on 2022-07-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, verbose_name='ответ на вопрос'),
        ),
    ]
