# Generated by Django 4.0.4 on 2022-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_event_is_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.TimeField(verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.TimeField(verbose_name='время окончания'),
        ),
    ]
