# Generated by Django 4.0.4 on 2022-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='компания'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ready_meet',
            field=models.BooleanField(default=False, verbose_name='готов знакомиться'),
        ),
    ]
