# Generated by Django 4.0.4 on 2022-08-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_profile_company_profile_job_profile_ready_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_speaker',
        ),
    ]
