# Generated by Django 4.0.4 on 2022-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_profile_is_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(max_length=50, null=True, verbose_name='телеграм имя'),
        ),
    ]
